name: CI/CD Pipeline

on: [push] # This triggers the workflow on any push to the repository

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Hello World! My first GitHub Action is working."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
